# Generated by Django 3.0.5 on 2020-05-10 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('component', 'component'), ('material', 'material')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_processing', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('pen', 'pen'), ('pencil', 'pencil')], max_length=50)),
                ('product_time_production', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.IntegerField(max_length=10)),
                ('element_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Element')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Element')),
                ('product_operations', models.ManyToManyField(through='apps.Operation', to='apps.Product')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.OperationsList'),
        ),
        migrations.AddField(
            model_name='operation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Product'),
        ),
        migrations.CreateModel(
            name='MaterialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.WarehouseMaterial')),
            ],
        ),
    ]
