# Generated by Django 3.0.5 on 2020-05-10 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(max_length=30)),
                ('lead_time_production', models.CharField(max_length=30)),
                ('production_start', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('создано', 'created'), ('запланировано', 'planed'), ('Процесс начат', 'process_finished'), ('Процесс завершён', 'process_finished'), ('Завершение заказа', 'finished')], default='created', max_length=50)),
                ('master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Product')),
            ],
        ),
    ]
