# Generated by Django 3.0.5 on 2020-05-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='type',
            field=models.CharField(choices=[('component', 'component'), ('material', 'material')], max_length=50),
        ),
    ]
