# Generated by Django 3.0.5 on 2020-05-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_productionorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='name',
            new_name='depiction',
        ),
        migrations.RemoveField(
            model_name='operationslist',
            name='element',
        ),
        migrations.AddField(
            model_name='operation',
            name='element',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apps.Element'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='element_quantity',
            field=models.IntegerField(default=10, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('Стержни', 'component'), ('Формы для карандашей', 'material'), ('Формы для ручек', 'material'), ('Краска', 'component')], max_length=50),
        ),
    ]
