# Generated by Django 3.0.5 on 2020-05-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200510_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_processing', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('pen', 'pen'), ('pencil', 'pencil')], max_length=50)),
                ('product_time_production', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperationsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50)),
                ('product_operations', models.ManyToManyField(through='apps.Operations', to='apps.Product')),
            ],
        ),
        migrations.AddField(
            model_name='operations',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.OperationsList'),
        ),
        migrations.AddField(
            model_name='operations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Product'),
        ),
    ]
