# Generated by Django 3.0.5 on 2020-05-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200510_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('rods', 'Стержни'), ('pencil shapes', 'Формы для карандашей'), ('pen shapes', 'Формы для ручек'), ('paint', 'Краска')], max_length=50),
        ),
    ]
