# Generated by Django 3.0.5 on 2020-05-11 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20200510_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_operation_ref', to='apps.Product'),
        ),
    ]
