# Generated by Django 3.0.5 on 2020-05-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20200511_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_ref', to='apps.Product'),
        ),
    ]
