# Generated by Django 3.0.5 on 2020-05-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('technologist', 'technologist'), ('dispatcher', 'dispatcher'), ('master_paint_workshop', 'master of the paint shop'), ('master_paint_workshop', 'master of the paint shop'), ('master_assembly_workshop', 'assembly shop master'), ('master_packing_workshop', 'packing shop master')], max_length=25),
        ),
    ]
